#!/bin/bash
# Bash configuration
# url github.com/sprngr/dotfiles

# Compiled from many sources and years of usage

df=~/.dotfiles

source $df/bash/path.sh
source $df/bash/env.sh
source $df/bash/completion.sh

source $df/bash/aliases.sh
source $df/bash/functions.sh
source $df/bash/prompt.sh

if [ -a $df/bash/work_aliases.sh ]; then
  source $df/bash/work_aliases.sh
fi
