#!/bin/bash
# Bash configuration
# url github.com/sprngr/dotfiles

# Compiled from many sources and years of usage

DOTFILES=~/.dotfiles

source $DOTFILES/bash/path.sh
source $DOTFILES/bash/env.sh
source $DOTFILES/bash/completion.sh

source $DOTFILES/bash/aliases.sh
source $DOTFILES/bash/functions.sh
source $DOTFILES/bash/prompt.sh

if [ -a $DOTFILES/bash/work_aliases.sh ]; then
  source $DOTFILES/bash/work_aliases.sh
fi
