"" Setup pathogen
call pathogen#incubate()
call pathogen#helptags()

"" Mappings for command-t
noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>

"" Closetag configuration
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako
source ~/.vim/bundle/closetag/plugin/closetag.vim

"" Tagbar config
let g:tagbar_usearrows = 1
noremap <leader>l :TagbarToggle<CR>

"" vim-javascript config
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
